services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  mysql:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_USER: ${MYSQL_ROOT_USERNAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      TZ: Asia/Taipei
    ports:
      - "33060:3306"
    volumes:
      - mysql-database:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
  postgres:
    image: postgres:16
    env_file: ./.env
    environment:
      TZ: "Asia/Taipei"
      PGTZ: "Asia/Taipei"
      POSTGRES_USER: ${PGSQL_USERNAME}
      POSTGRES_PASSWORD: ${PGSQL_PASSWORD}
      POSTGRES_DATABASE: ${PGSQL_DATABASE}
    ports:
      - "${PGSQL_PORT}:5432"
    volumes:
      - postgres-database:/var/lib/postgresql/data
      - ./.docker/postgres:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${PGSQL_USERNAME}" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  mysql-database:
  postgres-database:
