services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  mysql:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_USER: ${MYSQL_ROOT_USERNAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      TZ: Asia/Taipei
    ports:
      - "33060:3306"
    volumes:
      - mysql-database:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql-database:
