server:
  port: 8080

spring:
  application:
    name: demo
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true

info:
  app:
    name: spring_boot_demo
    version: 1.0.0
    description: A demo application for Spring Boot
