server:
  port: 8080

spring:
  application:
    name: demo
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

# custom properties
coach:
  name: whatever coach
team:
  name: whatever team
