server:
  port: 8080
  # servlet:
  #   context-path: /api

spring:
  application:
    name: demo
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  docker:
    compose:
      lifecycle-management: none

# logging
# logging:
#   level:
#     org:
#       springframework: DEBUG
#       hibernate: DEBUG
#     com:
#       zane: INFO
#   file:
#     name: logs/app.log

# custom properties
coach:
  name: whatever coach
team:
  name: whatever team
