server:
  port: 8080
  # servlet:
  #   context-path: /api

spring:
  application:
    name: demo
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  datasource:
    url: ${PGSQL_URL}
    username: ${PGSQL_USERNAME}
    password: ${PGSQL_PASSWORD}
    driver-class-name: org.postgresql.Driver
  main:
    banner-mode: off

# logging
logging:
  level:
    root: warn
#    org:
#       springframework: DEBUG
#       hibernate: DEBUG
#     com:
#       zane: INFO
#   file:
#     name: logs/app.log

# custom properties
coach:
  name: whatever coach
team:
  name: whatever team
